;this file for FamiTone2 libary generated by nsf2data tool

music:
	.word @song_ntsc_0, @song_pal_0

@song_ntsc_0:
	.byte $86,$81,$87,$93,$88,$01,$12,$87,$67,$18,$87,$2d,$1e,$00
@song_pal_0:
	.byte $86,$81,$87,$76,$88,$01,$0f,$87,$4d,$14,$87,$18,$19,$00
