;this file for FamiTone2 libary generated by nsf2data tool

sounds:
	.word @sfx_ntsc_0, @sfx_pal_0
	.word @sfx_ntsc_1, @sfx_pal_1
	.word @sfx_ntsc_2, @sfx_pal_2
	.word @sfx_ntsc_3, @sfx_pal_3
	.word @sfx_ntsc_4, @sfx_pal_4
	.word @sfx_ntsc_5, @sfx_pal_5
	.word @sfx_ntsc_6, @sfx_pal_6

;wall hit
@sfx_ntsc_0:
	.byte $89,$3e,$8a,$0b,$01,$89,$3c,$01,$89,$3a,$01,$89,$38,$01,$89,$36
	.byte $01,$89,$35,$07,$00
@sfx_pal_0:
	.byte $89,$3e,$8a,$0b,$01,$89,$3c,$01,$89,$3a,$01,$89,$38,$01,$89,$36
	.byte $01,$89,$35,$05,$00

;paddle hit
@sfx_ntsc_1:
	.byte $86,$81,$87,$52,$88,$01,$0c,$00
@sfx_pal_1:
	.byte $86,$81,$87,$3a,$88,$01,$0a,$00

;brick hit 1
@sfx_ntsc_2:
	.byte $86,$81,$87,$93,$88,$01,$0c,$00
@sfx_pal_2:
	.byte $86,$81,$87,$76,$88,$01,$0a,$00
	
;brick hit 2
@sfx_ntsc_3:
	.byte $86,$81,$87,$67,$88,$01,$0c,$00
@sfx_pal_3:
	.byte $86,$81,$87,$4d,$88,$01,$0a,$00

;brick hit 2
@sfx_ntsc_4:
	.byte $86,$81,$87,$2d,$88,$01,$0c,$00
@sfx_pal_4:
	.byte $86,$81,$87,$18,$88,$01,$0a,$00

;game over
@sfx_ntsc_5:
	.byte $86,$81,$87,$93,$88,$01,$12,$87,$67,$18,$87,$2d,$1e,$00
@sfx_pal_5:
	.byte $86,$81,$87,$76,$88,$01,$0f,$87,$4d,$14,$87,$18,$19,$00

;miss
@sfx_ntsc_6:
	.byte $86,$81,$87,$7e,$88,$00,$12,$00
@sfx_pal_6:
	.byte $86,$81,$87,$75,$88,$00,$0f,$00
