name: NES CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    container: debian:bullseye

    steps:
      - name: Checkout the branch
        uses: actions/checkout@v3
      - name: Setup Dev Environment
        run: |
          apt update && apt install -y build-essential git
          git clone https://github.com/cc65/cc65.git && cd cc65 && make && make avail

      - name: Analyze Project Metadata
        run: |
          echo "PROJECT_VERSION=$(head -n 1 ./VERSION)" >> $GITHUB_ENV
              
      - name: Build & Package Game
        run: |
          cd build
          sh build.sh

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.PROJECT_VERSION }}
          release_name: ${{ env.PROJECT_VERSION }}
          draft: false
          prerelease: false

      - name: Upload NES ROM ZIP
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/main.nes
          asset_name: ${{ github.event.repository.name }}-${{ env.PROJECT_VERSION }}.nes
          asset_content_type: application/x-nes-rom